import localFont from "next/font/local";
import "./globals.css";



const getisInter = localFont({
  src: "./fonts/inter.woff",
  variable: "--font-geist-inter",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${getisInter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
